package com.example.testvaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.TextFileProperty;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;

public class DocEditor extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TabSheet wysiwyg;
	@AutoGenerated
	private TextArea html;
	@AutoGenerated
	private RichTextArea wysiwyg1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public DocEditor() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public void setPropertyDataSource(TextFileProperty doc){
	
		html.setPropertyDataSource(doc);
		wysiwyg1.setPropertyDataSource(doc);
		
	}
	

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// wysiwyg
		wysiwyg = buildWysiwyg();
		mainLayout.addComponent(wysiwyg, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildWysiwyg() {
		// common part: create layout
		wysiwyg = new TabSheet();
		wysiwyg.setImmediate(true);
		wysiwyg.setWidth("440px");
		wysiwyg.setHeight("280px");
		
		// wysiwyg1
		wysiwyg1 = new RichTextArea();
		wysiwyg1.setImmediate(false);
		wysiwyg1.setWidth("100.0%");
		wysiwyg1.setHeight("100.0%");
		wysiwyg.addTab(wysiwyg1, "WYSIWYG", null);
		
		// html
		html = new TextArea();
		html.setImmediate(false);
		html.setWidth("100.0%");
		html.setHeight("100.0%");
		wysiwyg.addTab(html, "HTML", null);
		
		return wysiwyg;
	}

}
